version: '3.8'

services:
  client:
    container_name: test-client
    restart: unless-stopped
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/app
      - /node_modules
